# Generated by Django 4.2.20 on 2025-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('readed', models.IntegerField(default=0)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('en', models.IntegerField(default=0)),
            ],
        ),
    ]
